#!/usr/bin/env python3
"""Generate the README CLI reference and config reference from code.

The README's two generated sections sit between marker comments:

    <!-- BEGIN GENERATED: cli-reference -->  ...  <!-- END GENERATED: cli-reference -->
    <!-- BEGIN GENERATED: config-reference --> ... <!-- END GENERATED: config-reference -->

Everything outside the markers is hand-written and untouched.

The CLI reference is introspected from the click command tree
(``kstrl.cli:cli``), so a command that does not exist cannot be
documented and a new command cannot be silently omitted.

The config reference is verified behaviorally, not transcribed: for
every documented ``[section]`` key the script writes a sentinel value
into a throwaway kstrl.toml, runs the real loader, and asserts the
resolved config changed. It also probes every *undocumented* dataclass
field name of the per-section configs and fails if one turns out to be
a live toml key. Defaults shown in the output come from the dataclass
default instances. A key that stops working, changes its default, or
gets added without documentation makes regeneration produce a diff (or
an error), which CI catches.

Usage:
    uv run python scripts/gen_docs.py            # rewrite README.md in place
    uv run python scripts/gen_docs.py --check    # exit 1 if README.md is stale
"""

from __future__ import annotations

import argparse
import dataclasses
import os
import sys
import tempfile
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import click

# #261: the gate defaults are stated in exactly one place. Importing
# them keeps this reference from drifting the way it had: it claimed
# "uv run ruff check" without the path argument the gate actually
# passes, and named only the scoped branch of the typecheck default.
from kstrl.gateparse import GATE_LINT, GATE_TEST, GATE_TOOLS, GATE_TYPECHECK
from kstrl.verify import (
    DEFAULT_LINT_COMMAND,
    DEFAULT_TEST_COMMAND,
    DEFAULT_TYPECHECK_COMMAND,
    SCOPED_TYPECHECK_COMMAND,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"

GENERATED_NOTE = "<!-- Generated by scripts/gen_docs.py - do not edit by hand. -->"


def _marker(name: str, end: bool = False) -> str:
    return f"<!-- {'END' if end else 'BEGIN'} GENERATED: {name} -->"


# ---------------------------------------------------------------------------
# CLI reference (click introspection)
# ---------------------------------------------------------------------------


def _iter_commands(
    group: click.Group,
    prefix: str,
) -> Iterator[tuple[str, click.Command]]:
    """Yield (full command path, command) for every leaf command, depth-first."""
    for name in sorted(group.commands):
        cmd = group.commands[name]
        path = f"{prefix} {name}"
        if isinstance(cmd, click.Group):
            yield from _iter_commands(cmd, path)
        else:
            yield path, cmd


def _usage_suffix(cmd: click.Command, path: str) -> str:
    """Return the argument part of a command's usage line (no [OPTIONS])."""
    ctx = click.Context(cmd, info_name=path)
    pieces = [p for p in cmd.collect_usage_pieces(ctx) if p != "[OPTIONS]"]
    return (" " + " ".join(pieces)) if pieces else ""


def build_cli_reference() -> str:
    from kstrl.cli import cli

    entries: list[tuple[str, str]] = []
    for path, cmd in _iter_commands(cli, "ks"):
        invocation = f"{path}{_usage_suffix(cmd, path)}"
        entries.append((invocation, cmd.get_short_help_str(limit=120)))

    width = max(len(invocation) for invocation, _ in entries) + 2
    lines = [f"{invocation:<{width}}{help_text}" for invocation, help_text in entries]
    body = "\n".join(lines)
    return (
        f"{GENERATED_NOTE}\n\n"
        f"```\n{body}\n```\n\n"
        "Run `ks COMMAND --help` for the full option list of any command.\n"
    )


# ---------------------------------------------------------------------------
# Config reference (dataclass defaults + behavioral toml-key probing)
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class SectionSpec:
    """One documented kstrl.toml section.

    ``keys`` maps toml key -> dataclass field name. ``loader`` is the
    real load(root_dir) classmethod, ``defaults`` the raw default
    instance whose field values are rendered as the documented defaults.
    """

    section: str
    title: str
    keys: dict[str, str]
    loader: Callable[[Path], Any]
    defaults: Any
    probe_undocumented_fields: bool


def _all_field_names(cfg_cls: Any) -> list[str]:
    """Every field name on a config dataclass, in declaration order.

    Outside :func:`_section_specs` on purpose: an inline comprehension
    per spec is what made that function's complexity grow with every
    section registered, and both complexity gates measure it.
    """
    return [f.name for f in dataclasses.fields(cfg_cls)]


def _section_specs() -> list[SectionSpec]:
    from kstrl.adequacy import AdequacyConfig
    from kstrl.autonomy import AutonomyConfig
    from kstrl.breaker import BreakerConfig
    from kstrl.config import KstrlConfig
    from kstrl.contract import ContractConfig
    from kstrl.divergence import DivergenceConfig
    from kstrl.evolution import EvolutionConfig
    from kstrl.factory import FactoryConfig
    from kstrl.feedforward import FeedforwardConfig
    from kstrl.fixtures import FixturesConfig
    from kstrl.inbox import InboxConfig
    from kstrl.intake_github import GitHubIntakeConfig
    from kstrl.knowledge import KnowledgeConfig
    from kstrl.linear import LinearConfig
    from kstrl.observability import NotifyConfig
    from kstrl.policy import PolicyConfig
    from kstrl.sandbox import SandboxConfig
    from kstrl.security import SecurityConfig
    from kstrl.serve import ServeConfig
    from kstrl.timeout import TimeoutConfig
    from kstrl.verify import VerifyConfig
    from kstrl.workqueue import QueueConfig

    def kstrl_loader(root: Path) -> Any:
        return KstrlConfig.load(root_dir=root)

    kstrl_defaults = KstrlConfig()

    def identity_keys(cfg_cls: Any, names: list[str]) -> dict[str, str]:
        field_names = {f.name for f in dataclasses.fields(cfg_cls)}
        missing = set(names) - field_names
        if missing:
            raise SystemExit(
                f"gen_docs spec error: {cfg_cls.__name__} has no fields {sorted(missing)}"
            )
        return {n: n for n in names}

    specs = [
        # KstrlConfig fans out over five sections with renamed keys; the
        # key->field mapping is declared here and verified behaviorally.
        SectionSpec(
            "agent",
            "Agent selection",
            {
                "type": "agent_type",
                "command": "agent_cmd",
                "model": "model",
                "reasoning_effort": "model_reasoning_effort",
                "budget_usd": "agent_budget_usd",
            },
            kstrl_loader,
            kstrl_defaults,
            probe_undocumented_fields=False,
        ),
        SectionSpec(
            "run",
            "Loop behavior",
            {
                "max_iterations": "max_iterations",
                "sleep_seconds": "sleep_seconds",
                "interactive": "interactive",
            },
            kstrl_loader,
            kstrl_defaults,
            probe_undocumented_fields=False,
        ),
        SectionSpec(
            "paths",
            "File locations",
            {
                "prompt": "prompt_file",
                "prd": "prd_file",
                "progress": "progress_file",
                "codebase_map": "codebase_map_file",
                "allowed": "allowed_paths",
            },
            kstrl_loader,
            kstrl_defaults,
            probe_undocumented_fields=False,
        ),
        SectionSpec(
            "git",
            "Branch handling",
            {"branch": "kstrl_branch", "auto_checkout": "auto_checkout"},
            kstrl_loader,
            kstrl_defaults,
            probe_undocumented_fields=False,
        ),
        SectionSpec(
            "ui",
            "Output rendering",
            {"ascii": "ascii_only"},
            kstrl_loader,
            kstrl_defaults,
            probe_undocumented_fields=False,
        ),
        SectionSpec(
            "timeout",
            "Timeout limits (seconds; 0 or less disables)",
            identity_keys(TimeoutConfig, _all_field_names(TimeoutConfig)),
            lambda root: TimeoutConfig.load(root_dir=root),
            TimeoutConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "factory",
            "Factory orchestration (Phase 0-3 pipeline)",
            identity_keys(
                FactoryConfig,
                [
                    "max_parallel",
                    "max_retries",
                    "retry_delay",
                    "use_worktrees",
                    "single_pr",
                    "create_prs",
                    "review_mode",
                    "setpoint_agreement",
                    "merge_timeout",
                    "max_adversarial_calls",
                    "max_total_tokens",
                    "max_cost_usd",
                    "pause_before_pr_merge",
                    "progress_log_enabled",
                    "keep_worktrees_on_failure",
                ],
            ),
            lambda root: FactoryConfig.load(root_dir=root),
            FactoryConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "breaker",
            "No-progress circuit breaker (R7.5; 0 iterations disables)",
            identity_keys(BreakerConfig, _all_field_names(BreakerConfig)),
            lambda root: BreakerConfig.load(root_dir=root),
            BreakerConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "sandbox",
            "OS-level agent sandboxing (R7.5; claude-code/codex only)",
            identity_keys(SandboxConfig, _all_field_names(SandboxConfig)),
            lambda root: SandboxConfig.load(root_dir=root),
            SandboxConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "verify",
            "Phase 1 mechanical verification",
            identity_keys(VerifyConfig, _all_field_names(VerifyConfig)),
            lambda root: VerifyConfig.load(root_dir=root),
            VerifyConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "fixtures",
            "Phase 1 approved-fixtures oracle (R7.2; default off)",
            identity_keys(FixturesConfig, _all_field_names(FixturesConfig)),
            lambda root: FixturesConfig.load(root_dir=root),
            FixturesConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "policy",
            "Phase 1 policy envelope (R8.1; opt-in)",
            identity_keys(PolicyConfig, _all_field_names(PolicyConfig)),
            lambda root: PolicyConfig.load(root_dir=root),
            PolicyConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "autonomy",
            "Autonomy ladder (R8.2; opt-in)",
            identity_keys(AutonomyConfig, _all_field_names(AutonomyConfig)),
            lambda root: AutonomyConfig.load(root_dir=root),
            AutonomyConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "inbox",
            "Exception inbox (R8.3)",
            identity_keys(InboxConfig, _all_field_names(InboxConfig)),
            lambda root: InboxConfig.load(root_dir=root),
            InboxConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "intake_github",
            "GitHub Issues remote inbox (R8.6)",
            identity_keys(GitHubIntakeConfig, _all_field_names(GitHubIntakeConfig)),
            lambda root: GitHubIntakeConfig.load(root_dir=root),
            GitHubIntakeConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "serve",
            "Continuous-intake daemon (R8.6)",
            identity_keys(ServeConfig, _all_field_names(ServeConfig)),
            lambda root: ServeConfig.load(root_dir=root),
            ServeConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "queue",
            "Continuous intake queue (R8.6)",
            identity_keys(QueueConfig, _all_field_names(QueueConfig)),
            lambda root: QueueConfig.load(root_dir=root),
            QueueConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "divergence",
            "Across-attempt review divergence detector (#265)",
            identity_keys(DivergenceConfig, _all_field_names(DivergenceConfig)),
            lambda root: DivergenceConfig.load(root_dir=root),
            DivergenceConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "adequacy",
            "Test-suite adequacy gate (R8.5; opt-in, advisory first)",
            identity_keys(AdequacyConfig, _all_field_names(AdequacyConfig)),
            lambda root: AdequacyConfig.load(root_dir=root),
            AdequacyConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "security",
            "Phase 2.5 security review",
            identity_keys(SecurityConfig, _all_field_names(SecurityConfig)),
            lambda root: SecurityConfig.load(root_dir=root),
            SecurityConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "contract",
            "Phase 3 cross-component contract testing",
            identity_keys(ContractConfig, _all_field_names(ContractConfig)),
            lambda root: ContractConfig.load(root_dir=root),
            ContractConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "feedforward",
            "Phase 0 feedforward (computational, no LLM)",
            identity_keys(
                FeedforwardConfig,
                _all_field_names(FeedforwardConfig),
            ),
            lambda root: FeedforwardConfig.load(root_dir=root),
            FeedforwardConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "knowledge",
            "Per-component knowledge layer",
            identity_keys(
                KnowledgeConfig,
                [
                    "enabled",
                    "max_core_tokens",
                    "max_dependency_tokens",
                    "max_sibling_tokens",
                    "distill_timeout_seconds",
                    "distill_model",
                    "max_facts_per_distill",
                    "dependency_scope",
                ],
            ),
            lambda root: KnowledgeConfig.load(root_dir=root),
            KnowledgeConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "evolution",
            "Continuous-learning journal",
            identity_keys(EvolutionConfig, _all_field_names(EvolutionConfig)),
            lambda root: EvolutionConfig.load(root_dir=root),
            EvolutionConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "notify",
            "Run-milestone notification hooks (R3.2)",
            identity_keys(NotifyConfig, _all_field_names(NotifyConfig)),
            lambda root: NotifyConfig.load(root_dir=root),
            NotifyConfig(),
            probe_undocumented_fields=True,
        ),
        SectionSpec(
            "linear",
            "Linear integration (R7.4; default off)",
            identity_keys(LinearConfig, _all_field_names(LinearConfig)),
            lambda root: LinearConfig.load(root_dir=root),
            LinearConfig(),
            probe_undocumented_fields=True,
        ),
    ]
    return specs


# One-line description per documented key. Regeneration fails when a key
# has no description, so new keys cannot land undocumented.
KEY_DESCRIPTIONS: dict[tuple[str, str], str] = {
    ("agent", "type"): '"claude-code" | "claude-sdk" | "codex"; empty/"auto" = auto-detect',
    ("agent", "command"): "custom agent shell command; overrides type",
    ("agent", "model"): 'e.g. "sonnet" (claude) or "gpt-5.5" (codex); empty = agent default',
    ("agent", "reasoning_effort"): "low | medium | high | max (model-dependent)",
    (
        "agent",
        "budget_usd",
    ): "in-loop USD ceiling; claude-sdk adapter only; empty/0 = unlimited (R7.6)",
    ("run", "max_iterations"): "iteration budget per component",
    ("run", "sleep_seconds"): "pause between iterations",
    ("run", "interactive"): "human-in-the-loop mode for the legacy loop",
    ("paths", "prompt"): "engineer prompt file",
    ("paths", "prd"): "PRD file",
    # Rendered as `progress = ""` because the dataclass default is None
    # (unset). Copying the generated line is therefore INERT - the empty
    # string is ignored by the loader. The previous rendering emitted the
    # live repo-root path, and copying THAT recreated the out-of-scope
    # defect this key's default was changed to avoid (review finding 1).
    ("paths", "progress"): "progress log the agent appends to; empty = each factory "
    "component writes beside its own PRD (inside its allowedPaths), "
    "set = that one path is forced on every component",
    ("paths", "codebase_map"): "brownfield codebase notes",
    ("paths", "allowed"): 'diff-scope allowlist, e.g. ["src/", "tests/"]; empty = unrestricted',
    ("git", "branch"): "branch override; empty = use PRD branchName",
    ("git", "auto_checkout"): "check the branch out automatically",
    ("ui", "ascii"): "ASCII separators only (no box-drawing characters)",
    ("timeout", "git_operation"): "per git subprocess",
    ("timeout", "agent_iteration"): "one engineer iteration",
    ("timeout", "component_total"): "wall clock per component across iterations",
    ("timeout", "verification_check"): "each Phase 1 check subprocess",
    ("timeout", "review_agent"): "Phase 2 reviewer call",
    ("timeout", "contract_test"): "Phase 3 contract test run",
    ("timeout", "subprocess_default"): "any other subprocess",
    (
        "timeout",
        "scheduler_backstop_margin",
    ): "extra slack before the scheduler declares a worker dead",
    ("factory", "max_parallel"): "concurrent component workers",
    ("factory", "max_retries"): "per-component retry budget across all phases",
    ("factory", "retry_delay"): "seconds between retry attempts",
    ("factory", "use_worktrees"): "isolate each component in .kstrl/worktrees/<run>/<id>",
    ("factory", "single_pr"): "one PR for the whole run instead of per-component",
    ("factory", "create_prs"): "push + merge PRs via gh",
    ("factory", "review_mode"): "hard | advisory | skip (Phase 2)",
    ("factory", "setpoint_agreement"): (
        "advisory | block: what to do when the reviewer does not confirm a "
        "story the engineer marked passes=true (R10.3)"
    ),
    ("factory", "merge_timeout"): "seconds to wait for PR merge confirmation",
    (
        "factory",
        "max_adversarial_calls",
    ): "cap on review+security+distill LLM calls; 0 = unbounded. "
    "At the cap a hard-mode review or security phase HALTS the component "
    "rather than merging it unreviewed; an advisory one skips. Budget 3 calls "
    "per component for hard review + hard security + knowledge (R10.5, "
    "docs/runbook.md)",
    (
        "factory",
        "max_total_tokens",
    ): "run-level token budget; 0 = unbounded. Counts cache reads at par, so "
    "it is a poor proxy for cost - prefer max_cost_usd. Halts before the "
    "next engineer iteration or phase, never mid-call (docs/env-vars.md)",
    ("factory", "max_cost_usd"): "run-level USD budget; 0 = unbounded. Same halt granularity as "
    "max_total_tokens (between iterations, not mid-call), so NOT a hard "
    "cap. Not [agent] budget_usd (docs/env-vars.md)",
    ("factory", "pause_before_pr_merge"): "human checkpoint before each PR (E6)",
    (
        "factory",
        "progress_log_enabled",
    ): "JSONL event log at .kstrl/progress.jsonl (R3.2); usage accounting is "
    "written either way (docs/env-vars.md)",
    (
        "factory",
        "keep_worktrees_on_failure",
    ): "keep failed components' worktrees for post-mortem (R3.3)",
    (
        "breaker",
        "no_progress_iterations",
    ): "halt after N consecutive no-progress iterations; 0 disables (R7.5)",
    ("breaker", "test_command"): "stall-probe command; empty = the explicit [verify] test_command, "
    "else diff-hash only",
    ("breaker", "test_timeout"): "seconds before the stall probe is killed",
    ("sandbox", "enabled"): "OS-sandbox the engineer's agent CLI (writes scoped to its "
    "worktree); ignored for custom agent commands",
    ("sandbox", "allow_network"): "re-open outbound network inside the sandbox (off = deny)",
    ("verify", "test_command"): f"empty = the harness default ({DEFAULT_TEST_COMMAND})",
    ("verify", "typecheck_command"): (
        f"empty = {SCOPED_TYPECHECK_COMMAND} when [tool.mypy] scopes it, "
        f"else {DEFAULT_TYPECHECK_COMMAND}"
    ),
    ("verify", "lint_command"): f"empty = the harness default ({DEFAULT_LINT_COMMAND})",
    ("verify", "test_tool"): "parser for the test gate's output; empty = every parser "
    f"({', '.join(GATE_TOOLS[GATE_TEST])}), unioned",
    ("verify", "typecheck_tool"): "parser for the typecheck gate's output; empty = every "
    f"parser ({', '.join(GATE_TOOLS[GATE_TYPECHECK])}), unioned",
    ("verify", "lint_tool"): "parser for the lint gate's output; empty = every parser "
    f"({', '.join(GATE_TOOLS[GATE_LINT])}), unioned",
    ("verify", "check_diff_scope"): "fail on changes outside allowed paths",
    ("verify", "check_bad_patterns"): "scan the diff for secret-like patterns",
    ("verify", "dead_code_cleanup"): "optional dead-code check",
    ("verify", "dead_code_command"): "empty = smart default when dead_code_cleanup is on",
    ("verify", "mutation_testing"): "optional mutation testing",
    ("verify", "mutation_threshold"): "minimum mutation kill rate (percent)",
    ("verify", "mutation_timeout"): "seconds for the mutation run",
    ("verify", "subprocess_timeout"): "seconds per verification subprocess",
    (
        "verify",
        "require_self_critique",
    ): "fail Phase 1 if the ## Self-Critique block is missing/sparse",
    ("verify", "self_critique_min_bullets"): "minimum substantive bullets in the block",
    ("verify", "progress_file_path"): "progress file the self-critique check reads; "
    "empty = the log beside the component's PRD",
    ("fixtures", "enabled"): "run PRD-defined fixtures during Phase 1 (sandboxed; opt-in)",
    ("fixtures", "snapshot_on_success"): "save passing outputs for cross-run regression comparison",
    ("fixtures", "snapshot_dir"): "relative paths resolve against the repo root",
    ("fixtures", "timeout"): "seconds per fixture subprocess",
    ("policy", "enabled"): "enforce the [policy] envelope in Phase 1 (opt-in)",
    ("policy", "paths_deny"): "globs no change may touch (gitignore-style **)",
    ("policy", "max_files_changed"): "max files in a change; negative disables",
    (
        "policy",
        "max_lines_changed",
    ): "max added+removed lines (lockfiles excluded); negative disables",
    ("policy", "deps_allow_new"): "allow new uv.lock packages (L3+ may enable)",
    ("policy", "secret_patterns"): "regexes flagged in added diff lines",
    (
        "policy",
        "enforcement_paths_extra",
    ): "extra halt paths; additive - cannot shrink the built-in set",
    ("policy", "license_allow"): "allowed SPDX ids for new deps (empty disables)",
    ("policy", "license_deny_partial"): "substrings that deny a dep license (copyleft)",
    ("policy", "license_unresolved"): "block | advisory when no source resolves a license",
    ("policy", "license_use_network"): "allow PyPI fallback; false = uv cache only",
    ("policy", "deploy"): "reserved for the R8.7 release gate; stored + hashed",
    ("autonomy", "enabled"): "derive run permissions from the ladder level (opt-in)",
    ("autonomy", "max_level"): "hard ceiling: never run above this level (1-4)",
    ("autonomy", "demote_on_calibration_regression"): (
        "demote one level when `calibration compare` finds a regression "
        "(an inbox item is opened either way)"
    ),
    ("autonomy", "demote_on_health_breach"): (
        "demote one level on an R8.4 health control-limit breach "
        "(an inbox item is opened either way)"
    ),
    ("inbox", "enabled"): "record exceptions awaiting a human decision",
    ("inbox", "open_item_cap"): "open items after which queue intake pauses; 0 = unbounded",
    ("inbox", "snooze_hours"): "default snooze TTL in hours; snoozed items return",
    ("inbox", "notify_action_required"): "notify on action-required items and demotions only",
    ("intake_github", "enabled"): "poll GitHub Issues for labelled work (opt-in outbound poller)",
    ("intake_github", "repo"): "owner/name to poll; empty resolves from the checkout's remote",
    ("intake_github", "queued_label"): "the trigger label; applying it requires repo write access",
    ("intake_github", "label_prefix"): "prefix for the state labels written back to the issue",
    ("intake_github", "max_items_per_sync"): "upper bound on items admitted per sync",
    ("intake_github", "default_priority"): "queue priority given to remote-sourced items",
    ("intake_github", "comment_on_result"): "post the queue's verdict back to the source issue",
    ("intake_github", "dry_run"): "poll and log, but send no labels or comments",
    ("intake_github", "timeout_seconds"): "per-gh-invocation timeout in seconds",
    (
        "serve",
        "poll_interval_seconds",
    ): "seconds between poll cycles when ks serve runs as a daemon",
    ("serve", "daily_budget_usd"): "hard stop on reported spend per local day; 0 = no cap",
    ("serve", "max_consecutive_poison"): "consecutive poisoned items that pause the whole queue",
    (
        "serve",
        "caffeinate",
    ): "hold caffeinate -i for each run so the machine cannot sleep mid-factory",
    ("serve", "factory_timeout_seconds"): "kill a factory run after this long; 0 = no timeout",
    (
        "serve",
        "allow_uncovered_cost",
    ): "run unattended even when no adapter reports cost, making the budget unenforceable",
    ("queue", "max_attempts"): "execution attempts per queue item before it is poisoned",
    (
        "queue",
        "lease_ttl_seconds",
    ): "claim validity in seconds; the reaper recovers anything past this",
    ("divergence", "mode"): "skip | advisory | block; advisory records a diverging retry loop, "
    "block fails the component instead of paying for another retry (#265)",
    (
        "divergence",
        "growth_steps",
    ): "consecutive steps required before the detector fires, so it needs "
    'growth_steps + 1 measured attempts; must be >= 1 (use mode = "skip" '
    "to disable); the default is a structural minimum, not a measured number",
    ("adequacy", "enabled"): "run the Layer 0 test-adequacy checks (opt-in)",
    ("adequacy", "layer0"): "advisory | block; the ladder can raise it, never lower",
    ("adequacy", "require_strong_oracle"): "each new test file needs one falsifiable assertion",
    ("adequacy", "flag_assertionless_tests"): "report tests that assert nothing at all",
    ("security", "mode"): "skip | advisory | hard",
    ("security", "agent_cmd"): "empty = inherit [agent]",
    ("security", "agent_type"): "empty = inherit [agent]",
    ("security", "model"): "empty = inherit [agent]",
    ("security", "timeout_seconds"): "reviewer call timeout",
    ("security", "fail_threshold"): "critical | high | medium | low (hard mode)",
    ("contract", "mode"): "tier | final | skip",
    ("contract", "test_command"): "integration test command on merged tiers",
    ("contract", "timeout"): "seconds per contract test run",
    ("feedforward", "enabled"): "inject structural context into the prompt",
    ("feedforward", "module_map"): "directory tree with LOC counts",
    ("feedforward", "public_interfaces"): "public symbols via Python ast",
    ("feedforward", "dependency_graph"): "internal import analysis (Python only)",
    ("feedforward", "conventions"): "extract from pyproject.toml, ruff.toml, ...",
    ("feedforward", "max_context_tokens"): "cap to avoid prompt bloat",
    ("knowledge", "enabled"): "distill + inject durable facts",
    ("knowledge", "max_core_tokens"): "current component's facts (full text)",
    ("knowledge", "max_dependency_tokens"): "dependency facts (full text)",
    ("knowledge", "max_sibling_tokens"): "other components' facts (first sentence)",
    ("knowledge", "distill_timeout_seconds"): "distiller call timeout",
    ("knowledge", "distill_model"): "empty = falls back to [agent].model",
    ("knowledge", "max_facts_per_distill"): "cap on facts written per component",
    ("knowledge", "dependency_scope"): "direct | transitive (E8)",
    ("evolution", "enabled"): "record run outcomes",
    ("evolution", "journal_path"): "JSONL journal location",
    ("evolution", "experiments_path"): "experiment tracker location",
    ("evolution", "min_pattern_frequency"): "pattern must recur N times before proposal",
    ("evolution", "lookback_runs"): "past runs to analyze",
    ("evolution", "auto_propose"): "generate proposals after each factory run",
    ("evolution", "auto_apply_computational"): "auto-apply computational proposals",
    ("notify", "on_complete"): "shell hook fired once when the run finishes; empty = disabled",
    ("notify", "on_first_failure"): "shell hook fired once on the first component failure",
    ("notify", "on_inbox_item"): "shell hook fired per R8.3 inbox item kind; empty = disabled",
    ("notify", "hook_timeout"): "seconds before a hook command is killed",
    ("linear", "enabled"): "mirror runs into Linear (project/issues/status via GitHub linking)",
    ("linear", "team_id"): "Linear team UUID (required when enabled)",
    ("linear", "token_env"): "NAME of the env var holding the API token",
    ("linear", "auth_mode"): "auto | api_key | oauth (auto sniffs the lin_api_ prefix)",
    ("linear", "api_url"): "GraphQL endpoint",
    ("linear", "dry_run"): "record mutations instead of sending them",
    ("linear", "timeout_seconds"): "per-request timeout",
    ("linear", "min_request_interval"): "client-side throttle between requests (seconds)",
}

# Sentinel values for keys whose loader validates the value (enum
# membership, or a typed check the generic type-derived sentinel would
# fail - e.g. budget_usd ignores non-numeric and non-positive values).
ENUM_SENTINELS: dict[tuple[str, str], str | float] = {
    ("agent", "type"): "codex",
    ("agent", "budget_usd"): 123.5,
    ("agent", "reasoning_effort"): "high",
    ("factory", "review_mode"): "advisory",
    ("factory", "setpoint_agreement"): "block",
    ("security", "mode"): "hard",
    ("security", "fail_threshold"): "low",
    ("policy", "license_unresolved"): "advisory",
    ("adequacy", "layer0"): "block",
    ("divergence", "mode"): "block",
    ("autonomy", "max_level"): 2,
    ("contract", "mode"): "final",
    ("knowledge", "dependency_scope"): "transitive",
    ("linear", "auth_mode"): "oauth",
    # intake_github.repo is validated as owner/name, so the generic
    # string sentinel is rejected by the loader.
    ("intake_github", "repo"): "sentinel-owner/sentinel-repo",
    # The three verify tool keys are validated against their gate's
    # registered parsers, so the probe has to use a real one. The SECOND
    # entry, never the first: the probe asserts the loaded value differs
    # from the default, and picking the primary would still differ from
    # None but reads as if the primary were special.
    ("verify", "test_tool"): GATE_TOOLS[GATE_TEST][1],
    ("verify", "typecheck_tool"): GATE_TOOLS[GATE_TYPECHECK][1],
    ("verify", "lint_tool"): GATE_TOOLS[GATE_LINT][1],
}


def _sentinel_for(section: str, key: str, default: Any) -> Any:
    if (section, key) in ENUM_SENTINELS:
        return ENUM_SENTINELS[(section, key)]
    if isinstance(default, bool):
        return not default
    if isinstance(default, int):
        return default + 7919
    if isinstance(default, float):
        return default + 1234.5
    if isinstance(default, list):
        return ["sentinel/path/"]
    # str, Path, or None (str-shaped in toml)
    return "sentinel-value"


def _toml_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_literal(v) for v in value) + "]"
    if value is None:
        return '""'
    if isinstance(value, Path):
        return f'"{value.as_posix()}"'
    return f'"{value}"'


@contextmanager
def _scrubbed_environ() -> Iterator[None]:
    """Run with an empty-ish environment so a developer's KSTRL_* / MODEL /
    NO_COLOR etc. cannot leak into the probed loaders (env beats toml)."""
    saved = dict(os.environ)
    keep = {"PATH", "HOME", "TMPDIR", "SystemRoot"}
    try:
        for name in list(os.environ):
            if name not in keep:
                del os.environ[name]
        yield
    finally:
        os.environ.clear()
        os.environ.update(saved)


def _write_probe_toml(path: Path, specs: list[SectionSpec], extra: dict[str, list[str]]) -> None:
    lines: list[str] = []
    for spec in specs:
        lines.append(f"[{spec.section}]")
        for key, field_name in spec.keys.items():
            default = getattr(spec.defaults, field_name)
            lines.append(f"{key} = {_toml_literal(_sentinel_for(spec.section, key, default))}")
        for key in extra.get(spec.section, ()):
            lines.append(f"{key} = {_toml_literal('sentinel-value')}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _scalar_fields(defaults: Any) -> set[str]:
    names: set[str] = set()
    for f in dataclasses.fields(defaults):
        value = getattr(defaults, f.name)
        if value is None or isinstance(value, (bool, int, float, str, Path, list)):
            names.add(f.name)
    return names


def _verify_sections(specs: list[SectionSpec]) -> None:
    """Behavioral check: every documented key changes the resolved config;
    no undocumented scalar field of a per-section config is a live toml key."""
    errors: list[str] = []
    extra: dict[str, list[str]] = {}
    for spec in specs:
        if spec.probe_undocumented_fields:
            candidates = _scalar_fields(spec.defaults) - set(spec.keys.values())
            # None-defaulted non-scalar handling: only str-shaped probes are
            # meaningful; every current config field is scalar or a sub-config.
            extra[spec.section] = sorted(candidates)

    with _scrubbed_environ(), tempfile.TemporaryDirectory() as tmp:
        # Baseline and probe load from the SAME root, differing only in
        # whether kstrl.toml exists: several configs resolve path fields
        # against root_dir, so loads from two different roots would
        # spuriously differ on fields the toml never touched.
        probe_root = Path(tmp) / "probe"
        probe_root.mkdir()
        toml_path = probe_root / "kstrl.toml"

        baselines = {spec.section: spec.loader(probe_root) for spec in specs}
        _write_probe_toml(toml_path, specs, extra)

        for spec in specs:
            baseline = baselines[spec.section]
            probed = spec.loader(probe_root)
            for key, field_name in spec.keys.items():
                if getattr(probed, field_name) == getattr(baseline, field_name):
                    errors.append(
                        f"[{spec.section}] {key}: documented but setting it in "
                        f"kstrl.toml did not change {type(baseline).__name__}.{field_name}"
                    )
            for field_name in extra.get(spec.section, ()):
                if getattr(probed, field_name) != getattr(baseline, field_name):
                    errors.append(
                        f"[{spec.section}] {field_name}: live toml key not documented "
                        "in scripts/gen_docs.py (add it to the section spec + description)"
                    )
            for key in spec.keys:
                if (spec.section, key) not in KEY_DESCRIPTIONS:
                    errors.append(f"[{spec.section}] {key}: missing KEY_DESCRIPTIONS entry")

    if errors:
        raise SystemExit("gen_docs config probing failed:\n  " + "\n  ".join(errors))


def build_config_reference() -> str:
    specs = _section_specs()
    _verify_sections(specs)

    blocks: list[str] = []
    for spec in specs:
        lines = [f"# {spec.title}", f"[{spec.section}]"]
        width = (
            max(
                len(f"{key} = {_toml_literal(getattr(spec.defaults, field_name))}")
                for key, field_name in spec.keys.items()
            )
            + 2
        )
        for key, field_name in spec.keys.items():
            assignment = f"{key} = {_toml_literal(getattr(spec.defaults, field_name))}"
            description = KEY_DESCRIPTIONS[(spec.section, key)]
            lines.append(f"{assignment:<{width}}# {description}")
        blocks.append("\n".join(lines))

    body = "\n\n".join(blocks)
    return (
        f"{GENERATED_NOTE}\n"
        "<!-- Defaults come from the config dataclasses; every key is probed\n"
        "     against the real loaders before this section is emitted. -->\n\n"
        f"```toml\n{body}\n```\n\n"
        "Environment variables override kstrl.toml, and CLI flags override both.\n"
        "See [docs/env-vars.md](docs/env-vars.md) for the full env-var mapping.\n"
    )


# ---------------------------------------------------------------------------
# README splicing
# ---------------------------------------------------------------------------


def _splice(text: str, name: str, generated: str) -> str:
    begin, end = _marker(name), _marker(name, end=True)
    if begin not in text or end not in text:
        raise SystemExit(f"README.md is missing the {begin} / {end} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{generated}{end}{tail}"


def render_readme(text: str) -> str:
    text = _splice(text, "cli-reference", build_cli_reference())
    text = _splice(text, "config-reference", build_config_reference())
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify README.md is current; exit 1 on drift without writing",
    )
    args = parser.parse_args(argv)

    current = README_PATH.read_text(encoding="utf-8")
    rendered = render_readme(current)

    if args.check:
        if rendered != current:
            sys.stderr.write(
                "README.md generated sections are stale.\nRun: uv run python scripts/gen_docs.py\n"
            )
            return 1
        print("README.md generated sections are current.")
        return 0

    if rendered != current:
        README_PATH.write_text(rendered, encoding="utf-8")
        print("README.md updated.")
    else:
        print("README.md already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
